name: Format Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  black_isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
      - uses: isort/isort-action@v1
        with:
            configuration: "--line-length=120 --profile black"